### ISSUE TITLE
Can't se brightness and color at the same time

### ISSUE THREAD

**Issue by valexi7** [jomwells/ambilights#7]
I'm trying to do this:
```
  action:
   service: light.turn_on
   entity_id: light.philips_ambilight
   data_template:
     brightness: '20'
     rgb_color: ['{{ (range(0, 255)|random) }}','{{ (range(0, 255)|random) }}','{{ (range(0, 255)|random) }}']
     transition: '{{ (range(5, 30)|random) }}'
```
But you can only set brightness or rgb_color in the same action.

Could you modify your code that if you are trying to set brightness and color to light component it would split them to two requests?
